version: "3"
services:

  pushgateway:
    image: prom/pushgateway:v1.3.0
    ports:
      - 9091:9091

  prometheus:
    image: prom/prometheus:v2.21.0
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:7.2.1
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=perf-gauge
